# Generated by Django 4.1.6 on 2023-02-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_faces_app', '0002_imagenes_bluredfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenes',
            old_name='bluredfile',
            new_name='archivo',
        ),
        migrations.RenameField(
            model_name='imagenes',
            old_name='file',
            new_name='archivoBlur',
        ),
    ]
